yamt/toywasm

- lib/wasi.c
The previous logic was broken.
It was returning EFAULT (which indicating a trap in memory_getptr) to the caller without processing the trap properly.
This commit fixes it by distinguishing user-level error and host-level error. EFAULT for traps is a host-level error.
cf. https://github.com/WebAssembly/WASI/issues/505
> wasi: raise a trap on out-of-range memory access

- lib/module.c
When populate_resulttype_cellidx/populate_localtype_cellidx failed, just go without indexes. While it might slow down execution, it isn't fatal. Especially for EOVERFLOW, which is an implementation limitation.
> Ignore cellidx failure

- lib/exec.c
- lib/instance.c
- lib/type.h
- wat/large_memory.wat.in
* don't bother to defer allocation to acctual access for large linear memory. realloc overhead is more troublesome.
* lift an implementation limit and allow to use the full 32-bit linear memory.  (on 64-bit platforms)
* reduce the number of 64-bit arithmetics in the fast path.
> a few linear memory related improvements

- lib/CMakeLists.txt
- lib/expr.c
- lib/insn_impl_base.h
- lib/load_context.c
- lib/load_context.h
- lib/module.c
- lib/validation.c
- lib/validation.h
this makes some differences for huge modules.
(eg. ffmpeg.wasm has 14294 functions)
without this change:
```
spacetanuki% time ./toywasm --wasi --load ../ffmpeg.wasm
u 0.18s s 0.01s e 0.20s maj 0 min 8156 in 0 out 0
spacetanuki% time ./toywasm --wasi --load ../ffmpeg.wasm
u 0.18s s 0.01s e 0.20s maj 0 min 8162 in 0 out 0
spacetanuki% time ./toywasm --wasi --load ../ffmpeg.wasm
u 0.18s s 0.01s e 0.19s maj 0 min 8373 in 0 out 0
spacetanuki% time ./toywasm --wasi --load ../ffmpeg.wasm
u 0.17s s 0.01s e 0.18s maj 0 min 8056 in 0 out 0
spacetanuki% time ./toywasm --wasi --load ../ffmpeg.wasm
u 0.18s s 0.01s e 0.19s maj 0 min 8423 in 0 out 0
```
with this change:
```
spacetanuki% time ./toywasm --wasi --load ../ffmpeg.wasm
u 0.16s s 0.01s e 0.17s maj 0 min 8120 in 0 out 0
spacetanuki% time …
```
> reuse validation context among exprs

- CMakeLists.txt
i'm a bit uncomfortable as this effectively makes our ci to rely on mozilla's ci artifact. but i guess it practically isn't a problem.
> add a test to run js.wasm

- lib/exec.c
for some reasons this restores about 5% performance regression for test/run-ffmpeg.sh
(the regression was introduced by b112428647aa1427a159f8090e98fb3e2673e10e)
i'm not sure how this small change can affect the performance this much. especially when i've heard that recent processors don't use this simple pentium4 style "use jump directions as branch hints" prediction anymore. (here in my environment "2.2 GHz 6-Core Intel Core i7" is used)
without this
```
spacetanuki% ./test/run-ffmpeg.sh /usr/bin/time -l ./b/toywasm --wasi --wasi-dir=.video --
83.77 real        83.71 user         0.04 sys
```
```
0000000100006e50 <_check_interrupt>:
100006e50: 48 8b 8f d0 00 00 00         movq    208(%rdi), %rcx
100006e57: 31 c0                        xorl    %eax, %eax
100006e59: 48 85 c9 …
```
> check_interrupt: add a branch hint

- lib/exec.c
- lib/exec.h
everything uses trap_with_id these days.
> retire trap()

- test/js-wasm.sh
for some reasons, we don't need to ungzip anymore. probably something has been changed on the server.
> test/js-wasm.sh: update

- lib/host_instance.c
also, fix a dec vs hex confusion
> host_func_dump_params: fix TOYWASM_USE_SMALL_CELLS case

- .github/workflows/ci.yml
The following runner image doesn't seem to have this file anymore.
```
Image: ubuntu-20.04
Version: 20240514.2.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20240514.2/images/ubuntu/Ubuntu2004-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20240514.2
```
> CI: tries to fix cross jobs

- lib/module.c
> read_dylink_0_section: reject duplicated sections/subsections

- lib/decode.c
- lib/exec_insn_subr.c
- lib/instance.c
- lib/mem.c
- lib/mem.h
- lib/util.c
- lib/util.h
- lib/validation.c
- lib/vec.c
in the most callsites, it's obvious which one should be used. there is little reason to leave it to the lower level api, mem_resize to decide which is the case.
while i'm here, fix the resize_array vs ARRAY_RESIZE naming inconsistency as well.
mem_resize -> mem_extend, mem_shrink
resize_array -> array_extend, array_shrink
ARRAY_RESIZE -> ARRAY_EXTEND
> mem_resize: separate to mem_extend and mem_shrink

- benchmark/startup.md
This fixes the file link to `startup.txt` which got renamed to `startup.csv`.
> Fix link to raw values in `startup.md`

- cli/main.c
the regression was introduced by
commit 217a733089efc18f2a75193552df74de1db0a8ed
("cli: use separate mem contexts for modules and instances")
> cli: fix --max-memory regression

- .github/workflows/ci.yml
This reverts commit 39a20131604cc87425140abb9e6c9d6314678a9b.
> Revert "ci: try installing qemu 7.0 from canonical server backports"

- lib/host_instance.h
it was not intentional and clang complained on it.
> HOST_FUNC_DECL: don't omit an argument

- lib/host_instance.h
- lib/module.c
- lib/module_writer.c
- lib/type.h
- libwasi/wasi_path_subr.h
> clang-format

- .github/workflows/ci.yml
cf. https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
fixes: https://github.com/yamt/toywasm/issues/285
> CI: update actions/upload-artifact download-artifact to v4

- CMakeLists.txt
make dsymutil works better for IPO-enabled libraries.
tested with Xcode 16.2, macOS 15.3.2, amd64
> fix debug info with IPO on macOS

- lib/exec.c
- lib/exec_debug.c
- lib/exec_insn_subr.c
- lib/expr.c
- lib/host_instance.c
- lib/insn_impl_control.h
- lib/insn_impl_tailcall.h
- lib/instance.c
- lib/module.c
- lib/type.c
- lib/type.h
- libwasi/wasi.c
- libwasi/wasi_abi_sock.c
- libwasi/wasi_host_fdop.c
- libwasi/wasi_path_subr.c
- libwasi_threads/wasi_threads.c
fix GCC warnings for the target with long uint32_t
Note: on some targets, int32_t is a long.
eg. GCC in the recent ESP-IDF has such a configuration.
```shell
spacetanuki% xtensa-esp32-elf-gcc --version
xtensa-esp32-elf-gcc (crosstool-NG esp-12.2.0_20230208) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
spacetanuki% xtensa-esp32-elf-gcc -dM -E - < /dev/null | grep -E "(SIZE|INT32)_TYPE"
#define __SIZE_TYPE__ unsigned int
#define __INT32_TYPE__ long int
#define __UINT32_TYPE__ long unsigned int
spacetanuki%
```
references:
https://github.com/apache/nuttx/pull/16022
https://docs.espressif.com/projects/esp-idf/en/stable/esp32/migratio …
> fix GCC warnings for the target with long uint32_t

- cmake/ToywasmConfig.cmake
- lib/leb128.c
- lib/module.c
- lib/name.c
- lib/platform.h
after updating Xcode to 16.3, it started to complain on
these UDs. (correctly)
as i can imagine no nice way to fix the issue, let's disable
the check for now.
alternativs:
* make these functions use void *.
i don't like it because it actually loosen type checks.
* make _read_vec_with_ctx_impl a macro.
it's too large to implement as a macro in my taste.
> suppress ubsan complaints on function type mismatches

- CMakeLists.txt
for some reasons,
https://registry-cdn.wapm.io/contents/mozilla/spidermonkey/0.0.1/build/spidermonkey.wasm now yields http 526.
this commit disables the test to make the ci green.
> cmake: comment out toywasm-cli-spidermonkey test

- libdyld/dyld.c
- libdyld/dyld.h
- test/dyld/fetch-and-run-test.sh
XXX this makes the linker fail for non-pie executables which don't export these globals. too strict?
> libdyld: implement __stack_low/__stack_high
