- libwasi/wasi.c
- libwasi/wasi_fdtable.c
to prepare an api to control stdio fds.
no functional changes at this point.
> restructure wasi_instance_create a bit

- test/run-wasm3-spec-test.sh
- test/run-wasm3-wasi-test.sh
Namely this change:
```
commit 6d7abdcda765cb19d507ebcf2a1069d69d4199fc
Author: YAMAMOTO Takashi <imuwoto@gmail.com>
Date:   Fri Apr 28 20:43:53 2023 +0900
run-spec-test.py: make tests fail on unexpected traps
```
> run-wasm3-spec-test.sh: update my fork of wasm3

- CMakeLists.txt
- cmake/ToywasmConfig.cmake
- lib/CMakeLists.txt
- lib/cell.h
- lib/context.c
- lib/decode.c
- lib/decode.h
- lib/exec.c
- lib/exec.h
- lib/expr.h
- lib/insn.c
- lib/insn_impl_base.h
- lib/lock.h
- lib/module.c
- lib/type.h
- lib/usched.c
- lib/validation.h
- lib/valtype.h
- lib/vec.c
- libwasi/wasi.c
- libwasi/wasi_threads.c
many of them are found by `clang -pedantic`.
> Fix random portability issues

- lib/exec.c
- lib/exec_context.h
- lib/insn.c
- lib/instance.c
- lib/instance.h
- lib/usched.c
- libwasi/wasi.c
- libwasi/wasi_threads.c
no functional changes are intended for now.
in future, i might add other restartable errors.
> introduce IS_RESTARTABLE macro

- libwasi/wasi_threads.c
if you use `toywasm --wasi --repl` and then use `:invoke` multiple times, it hangs because it effectively reuse a wasi-threads instance and thus the number of threads in the cluster gets wrong. this commit fixes it by moving some initialization from wasi_threads_instance_create to wasi_threads_setup_exec_context. it also fixes similar issue wrt trap propagation.
> fix repl :invoke with wasi-threads

- lib/insn.c
- lib/insn_impl_control.h
revisit: i guess this ought to be more generic.
> unreachable: include PC in the trap message

- lib/exec.c
- lib/exec.h
- lib/insn_impl_base.h
rename the old version to memory_grow2
> make memory_grow consistent with table_grow

- .github/workflows/ci.yml
not really testing the functionality yet
> ci: build test dyld

- cli/main.c
- cli/repl.c
- cli/repl.h
- examples/runwasi/main.c
- examples/runwasi/runwasi.c
- examples/runwasi/runwasi.h
- lib/dyld.c
- lib/dyld.h
- lib/vec.h
- libwasi/wasi.c
- libwasi/wasi.h
- libwasi/wasi_impl.h
> add a few dyld options

- lib/insn.c
- lib/insn_impl_control.h
- lib/insn_impl_tailcall.h
the change in "end" instruction might involve some performance regression.
> reduce code dup a bit

- .github/workflows/ci.yml
This reverts commit 0293d55ef9a8b26de413f6c0a28c60de69bcb49c.
> Revert "CI: disable riscv64 for now"

- examples/libdl/dlfcn.h
cf. https://github.com/WebAssembly/wasi-libc/pull/443
> examples/libdl: sync with the wasi-libc abi

- README.md
because it's broken.
cf. https://github.com/wasmerio/webassembly.sh/issues/128
> README.md: remove webassembly.sh stuff

- lib/exec.c
while the complaint seems valid, i don't want to fix it. (for now) i don't think it can be a practical problem.
> suppress a TSAN complaint

- lib/exec_insn_subr.c
- lib/instance.c
- lib/type.h
also, add a few memory-related comments.
> instance_print_stats: print a bit more info about linear memory

- cli/main.c
- lib/host_instance.c
- lib/xlog.c
- lib/xlog.h
> wrap xlog_tracing with an ifdef

- lib/exec_insn_subr.c
- lib/instance.c
- lib/module.c
- lib/type.c
- lib/type.h
- libdyld/dyld.c
A preparation for custom-page-sizes.
> Clean up page size related logic

- lib/insn_impl_fc.h
> insn_impl_fc.h: fix a few crashing bugs in validation

- .github/workflows/ci.yml
cf. https://github.com/yamt/toywasm/pull/238#issuecomment-2226868990
it seems imports.wast occasionally fails.
> CI: disable armhf full job as well

- lib/exec_insn_subr.c
fixes https://github.com/yamt/toywasm/issues/261
> memory_instance_getptr2: remove unnnecessary calculation

- cmake/ToywasmConfig.cmake
cf. https://github.com/llvm/llvm-project/issues/55781
> cmake: --no-wasm-opt for clang 20 or later

- libwasi/wasi_abi_fd.c
- libwasi/wasi_abi_path.c
- libwasi/wasi_subr.c
- libwasi/wasi_subr.h
- test/run-wasi-testsuite.sh
also, bump wasi-testsuite version
> libwasi: reject a few ambiguous fstflags combinations

- .github/workflows/ci.yml
- examples/layout/CMakeLists.txt
- examples/layout/layout.c
- wat/wasi/hello.wat
examine the given module and show some information about memory layout
eg.
```
memory [0] min 2 max 65536
global [  1] 00000000          GOT.data.internal.__memory_base
data   [  0] 00000400-00008988 .rodata
data   [  1] 00008988-00008af8 .data
global [  0] 000197a0          __stack_pointer
```
> Add examples/layout
